### ISSUE TITLE
Limit number of threads used

### ISSUE THREAD

**Issue by user895v** [gunrock/essentials#130]
Hello, I would like to try limit number of threads used per application. Let's say I want to use only **1 GPU** thread and then us **as many as possible** (or some fixed amount). Is this possible in essentials, if yes where exactly can I modify NUM OF THREADS used?

**Comment by neoblizz** [comment]
Hi, thanks for your interest.
Due to the way kernels are configured, for correctness reasons it is required for one to launch multiple threads for the algorithms to be functional. Some of those launch configurations are controlled by us (in essentials) and others are tuned by the library we're using.

So, this is not something we advise or support and will not be trivial to do.
