### ISSUE TITLE
`graph_t` views interface needs to be completed

### ISSUE THREAD

**Issue by neoblizz** [gunrock/essentials#50]
Look for the comments marked with `// XXX`:
https://github.com/gunrock/essentials/blob/master/include/gunrock/graph/coo.hxx#L35-L38

Files in question:
- https://github.com/gunrock/essentials/blob/master/include/gunrock/graph/coo.hxx
- https://github.com/gunrock/essentials/blob/master/include/gunrock/graph/csc.hxx

**Comment by neoblizz** [comment]
@cameronshinn this is what I need help with from COO/CSC side within Essentials. No rush, just assigning it to you.

**Comment by bkj** [comment]
Are `coo` matrices assumed to have sorted edges?

FWIW, in `scipy.sparse`, `coo` matrices aren't subscriptable -- eg, you can't get all of the outdoing edges for a vertex, you can't check whether an edge exists, etc.  I think because presumably 
 - if the edges aren't sorted, you can't do these things w/o a full linear scan of the edgelist 
 - if the edges are sorted, you're better off using a `csr` or `csc` for almost everything

**Comment by neoblizz** [comment]
> Are `coo` matrices assumed to have sorted edges?

Yes, right now it is sorted. For unsorted, I am thinking of adding the expensive search version.

> * if the edges are sorted, you're better off using a `csr` or `csc` for almost everything

I can see COO being useful to improve random access times.

**Comment by bkj** [comment]
> I can see COO being useful to improve random access times. 

Curious -- can you explain more what you mean there?  I'm guessing you mean COO will give you faster `get_source_vertex(edge_id)`?

**Comment by neoblizz** [comment]
> Curious -- can you explain more what you mean there? I'm guessing you mean COO will give you faster `get_source_vertex(edge_id)`?

Yes, `get_source_vertex()` instead of being a search becomes a look up.

**Comment by bkj** [comment]
COO implemented in this PR: https://github.com/gunrock/essentials/pull/62
Note the problem re: empty graph views -- presumably that's easy to fix.

**Comment by neoblizz** [comment]
I believe the past PRs take care of this issue? Re-open if I am wrong about it.
